/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthOnboardingImport } from './routes/_auth/onboarding'
import { Route as AuthDemoReminderImport } from './routes/_auth/demo-reminder'
import { Route as AuthAppImport } from './routes/_auth/_app'
import { Route as AuthAppTemplateImport } from './routes/_auth/_app/template'
import { Route as AuthAppDashboardImport } from './routes/_auth/_app/dashboard'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthOnboardingRoute = AuthOnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDemoReminderRoute = AuthDemoReminderImport.update({
  id: '/demo-reminder',
  path: '/demo-reminder',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAppRoute = AuthAppImport.update({
  id: '/_app',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAppTemplateRoute = AuthAppTemplateImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => AuthAppRoute,
} as any)

const AuthAppDashboardRoute = AuthAppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_app': {
      id: '/_auth/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAppImport
      parentRoute: typeof AuthImport
    }
    '/_auth/demo-reminder': {
      id: '/_auth/demo-reminder'
      path: '/demo-reminder'
      fullPath: '/demo-reminder'
      preLoaderRoute: typeof AuthDemoReminderImport
      parentRoute: typeof AuthImport
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_app/dashboard': {
      id: '/_auth/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthAppDashboardImport
      parentRoute: typeof AuthAppImport
    }
    '/_auth/_app/template': {
      id: '/_auth/_app/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof AuthAppTemplateImport
      parentRoute: typeof AuthAppImport
    }
  }
}

// Create and export the route tree

interface AuthAppRouteChildren {
  AuthAppDashboardRoute: typeof AuthAppDashboardRoute
  AuthAppTemplateRoute: typeof AuthAppTemplateRoute
}

const AuthAppRouteChildren: AuthAppRouteChildren = {
  AuthAppDashboardRoute: AuthAppDashboardRoute,
  AuthAppTemplateRoute: AuthAppTemplateRoute,
}

const AuthAppRouteWithChildren =
  AuthAppRoute._addFileChildren(AuthAppRouteChildren)

interface AuthRouteChildren {
  AuthAppRoute: typeof AuthAppRouteWithChildren
  AuthDemoReminderRoute: typeof AuthDemoReminderRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppRoute: AuthAppRouteWithChildren,
  AuthDemoReminderRoute: AuthDemoReminderRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthAppRouteWithChildren
  '/demo-reminder': typeof AuthDemoReminderRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/dashboard': typeof AuthAppDashboardRoute
  '/template': typeof AuthAppTemplateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthAppRouteWithChildren
  '/demo-reminder': typeof AuthDemoReminderRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/dashboard': typeof AuthAppDashboardRoute
  '/template': typeof AuthAppTemplateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/_app': typeof AuthAppRouteWithChildren
  '/_auth/demo-reminder': typeof AuthDemoReminderRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/_app/dashboard': typeof AuthAppDashboardRoute
  '/_auth/_app/template': typeof AuthAppTemplateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/demo-reminder'
    | '/onboarding'
    | '/dashboard'
    | '/template'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/demo-reminder' | '/onboarding' | '/dashboard' | '/template'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/_app'
    | '/_auth/demo-reminder'
    | '/_auth/onboarding'
    | '/_auth/_app/dashboard'
    | '/_auth/_app/template'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_app",
        "/_auth/demo-reminder",
        "/_auth/onboarding"
      ]
    },
    "/_auth/_app": {
      "filePath": "_auth/_app.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_app/dashboard",
        "/_auth/_app/template"
      ]
    },
    "/_auth/demo-reminder": {
      "filePath": "_auth/demo-reminder.tsx",
      "parent": "/_auth"
    },
    "/_auth/onboarding": {
      "filePath": "_auth/onboarding.tsx",
      "parent": "/_auth"
    },
    "/_auth/_app/dashboard": {
      "filePath": "_auth/_app/dashboard.tsx",
      "parent": "/_auth/_app"
    },
    "/_auth/_app/template": {
      "filePath": "_auth/_app/template.tsx",
      "parent": "/_auth/_app"
    }
  }
}
ROUTE_MANIFEST_END */
