/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPaymentSuccessRouteImport } from './routes/_auth/payment-success'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthFeedbackRouteImport } from './routes/_auth/feedback'
import { Route as AuthAppRouteImport } from './routes/_auth/_app'
import { Route as AuthOnboardingIndexRouteImport } from './routes/_auth/onboarding/index'
import { Route as AuthOnboardingStepRouteImport } from './routes/_auth/onboarding/_step'
import { Route as AuthOnboardingNostepRouteImport } from './routes/_auth/onboarding/_nostep'
import { Route as AuthAppTemplateRouteImport } from './routes/_auth/_app/template'
import { Route as AuthAppDashboardRouteImport } from './routes/_auth/_app/dashboard'
import { Route as AuthOnboardingStepStepRouteImport } from './routes/_auth/onboarding/_step/$step'
import { Route as AuthOnboardingNostepWelcomeRouteImport } from './routes/_auth/onboarding/_nostep/welcome'
import { Route as AuthOnboardingNostepFeedbackRouteImport } from './routes/_auth/onboarding/_nostep/feedback'
import { Route as AuthOnboardingNostepCompletedRouteImport } from './routes/_auth/onboarding/_nostep/completed'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPaymentSuccessRoute = AuthPaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFeedbackRoute = AuthFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppRoute = AuthAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingIndexRoute = AuthOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingStepRoute = AuthOnboardingStepRouteImport.update({
  id: '/_step',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingNostepRoute = AuthOnboardingNostepRouteImport.update({
  id: '/_nostep',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthAppTemplateRoute = AuthAppTemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppDashboardRoute = AuthAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthOnboardingStepStepRoute = AuthOnboardingStepStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => AuthOnboardingStepRoute,
} as any)
const AuthOnboardingNostepWelcomeRoute =
  AuthOnboardingNostepWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AuthOnboardingNostepRoute,
  } as any)
const AuthOnboardingNostepFeedbackRoute =
  AuthOnboardingNostepFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthOnboardingNostepRoute,
  } as any)
const AuthOnboardingNostepCompletedRoute =
  AuthOnboardingNostepCompletedRouteImport.update({
    id: '/completed',
    path: '/completed',
    getParentRoute: () => AuthOnboardingNostepRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/feedback': typeof AuthFeedbackRoute
  '/onboarding': typeof AuthOnboardingStepRouteWithChildren
  '/payment-success': typeof AuthPaymentSuccessRoute
  '/dashboard': typeof AuthAppDashboardRoute
  '/template': typeof AuthAppTemplateRoute
  '/onboarding/': typeof AuthOnboardingIndexRoute
  '/onboarding/completed': typeof AuthOnboardingNostepCompletedRoute
  '/onboarding/feedback': typeof AuthOnboardingNostepFeedbackRoute
  '/onboarding/welcome': typeof AuthOnboardingNostepWelcomeRoute
  '/onboarding/$step': typeof AuthOnboardingStepStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/feedback': typeof AuthFeedbackRoute
  '/payment-success': typeof AuthPaymentSuccessRoute
  '/dashboard': typeof AuthAppDashboardRoute
  '/template': typeof AuthAppTemplateRoute
  '/onboarding': typeof AuthOnboardingIndexRoute
  '/onboarding/completed': typeof AuthOnboardingNostepCompletedRoute
  '/onboarding/feedback': typeof AuthOnboardingNostepFeedbackRoute
  '/onboarding/welcome': typeof AuthOnboardingNostepWelcomeRoute
  '/onboarding/$step': typeof AuthOnboardingStepStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/loading': typeof LoadingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_auth/_app': typeof AuthAppRouteWithChildren
  '/_auth/feedback': typeof AuthFeedbackRoute
  '/_auth/onboarding': typeof AuthOnboardingRouteWithChildren
  '/_auth/payment-success': typeof AuthPaymentSuccessRoute
  '/_auth/_app/dashboard': typeof AuthAppDashboardRoute
  '/_auth/_app/template': typeof AuthAppTemplateRoute
  '/_auth/onboarding/_nostep': typeof AuthOnboardingNostepRouteWithChildren
  '/_auth/onboarding/_step': typeof AuthOnboardingStepRouteWithChildren
  '/_auth/onboarding/': typeof AuthOnboardingIndexRoute
  '/_auth/onboarding/_nostep/completed': typeof AuthOnboardingNostepCompletedRoute
  '/_auth/onboarding/_nostep/feedback': typeof AuthOnboardingNostepFeedbackRoute
  '/_auth/onboarding/_nostep/welcome': typeof AuthOnboardingNostepWelcomeRoute
  '/_auth/onboarding/_step/$step': typeof AuthOnboardingStepStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loading'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/feedback'
    | '/onboarding'
    | '/payment-success'
    | '/dashboard'
    | '/template'
    | '/onboarding/'
    | '/onboarding/completed'
    | '/onboarding/feedback'
    | '/onboarding/welcome'
    | '/onboarding/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loading'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/feedback'
    | '/payment-success'
    | '/dashboard'
    | '/template'
    | '/onboarding'
    | '/onboarding/completed'
    | '/onboarding/feedback'
    | '/onboarding/welcome'
    | '/onboarding/$step'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/loading'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/_auth/_app'
    | '/_auth/feedback'
    | '/_auth/onboarding'
    | '/_auth/payment-success'
    | '/_auth/_app/dashboard'
    | '/_auth/_app/template'
    | '/_auth/onboarding/_nostep'
    | '/_auth/onboarding/_step'
    | '/_auth/onboarding/'
    | '/_auth/onboarding/_nostep/completed'
    | '/_auth/onboarding/_nostep/feedback'
    | '/_auth/onboarding/_nostep/welcome'
    | '/_auth/onboarding/_step/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoadingRoute: typeof LoadingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/payment-success': {
      id: '/_auth/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof AuthPaymentSuccessRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/feedback': {
      id: '/_auth/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthFeedbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_app': {
      id: '/_auth/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAppRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/': {
      id: '/_auth/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthOnboardingIndexRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/_step': {
      id: '/_auth/onboarding/_step'
      path: ''
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingStepRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/_nostep': {
      id: '/_auth/onboarding/_nostep'
      path: ''
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingNostepRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/_app/template': {
      id: '/_auth/_app/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof AuthAppTemplateRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/_app/dashboard': {
      id: '/_auth/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthAppDashboardRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/onboarding/_step/$step': {
      id: '/_auth/onboarding/_step/$step'
      path: '/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof AuthOnboardingStepStepRouteImport
      parentRoute: typeof AuthOnboardingStepRoute
    }
    '/_auth/onboarding/_nostep/welcome': {
      id: '/_auth/onboarding/_nostep/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof AuthOnboardingNostepWelcomeRouteImport
      parentRoute: typeof AuthOnboardingNostepRoute
    }
    '/_auth/onboarding/_nostep/feedback': {
      id: '/_auth/onboarding/_nostep/feedback'
      path: '/feedback'
      fullPath: '/onboarding/feedback'
      preLoaderRoute: typeof AuthOnboardingNostepFeedbackRouteImport
      parentRoute: typeof AuthOnboardingNostepRoute
    }
    '/_auth/onboarding/_nostep/completed': {
      id: '/_auth/onboarding/_nostep/completed'
      path: '/completed'
      fullPath: '/onboarding/completed'
      preLoaderRoute: typeof AuthOnboardingNostepCompletedRouteImport
      parentRoute: typeof AuthOnboardingNostepRoute
    }
  }
}

interface AuthAppRouteChildren {
  AuthAppDashboardRoute: typeof AuthAppDashboardRoute
  AuthAppTemplateRoute: typeof AuthAppTemplateRoute
}

const AuthAppRouteChildren: AuthAppRouteChildren = {
  AuthAppDashboardRoute: AuthAppDashboardRoute,
  AuthAppTemplateRoute: AuthAppTemplateRoute,
}

const AuthAppRouteWithChildren =
  AuthAppRoute._addFileChildren(AuthAppRouteChildren)

interface AuthOnboardingNostepRouteChildren {
  AuthOnboardingNostepCompletedRoute: typeof AuthOnboardingNostepCompletedRoute
  AuthOnboardingNostepFeedbackRoute: typeof AuthOnboardingNostepFeedbackRoute
  AuthOnboardingNostepWelcomeRoute: typeof AuthOnboardingNostepWelcomeRoute
}

const AuthOnboardingNostepRouteChildren: AuthOnboardingNostepRouteChildren = {
  AuthOnboardingNostepCompletedRoute: AuthOnboardingNostepCompletedRoute,
  AuthOnboardingNostepFeedbackRoute: AuthOnboardingNostepFeedbackRoute,
  AuthOnboardingNostepWelcomeRoute: AuthOnboardingNostepWelcomeRoute,
}

const AuthOnboardingNostepRouteWithChildren =
  AuthOnboardingNostepRoute._addFileChildren(AuthOnboardingNostepRouteChildren)

interface AuthOnboardingStepRouteChildren {
  AuthOnboardingStepStepRoute: typeof AuthOnboardingStepStepRoute
}

const AuthOnboardingStepRouteChildren: AuthOnboardingStepRouteChildren = {
  AuthOnboardingStepStepRoute: AuthOnboardingStepStepRoute,
}

const AuthOnboardingStepRouteWithChildren =
  AuthOnboardingStepRoute._addFileChildren(AuthOnboardingStepRouteChildren)

interface AuthOnboardingRouteChildren {
  AuthOnboardingNostepRoute: typeof AuthOnboardingNostepRouteWithChildren
  AuthOnboardingStepRoute: typeof AuthOnboardingStepRouteWithChildren
  AuthOnboardingIndexRoute: typeof AuthOnboardingIndexRoute
}

const AuthOnboardingRouteChildren: AuthOnboardingRouteChildren = {
  AuthOnboardingNostepRoute: AuthOnboardingNostepRouteWithChildren,
  AuthOnboardingStepRoute: AuthOnboardingStepRouteWithChildren,
  AuthOnboardingIndexRoute: AuthOnboardingIndexRoute,
}

const AuthOnboardingRouteWithChildren = AuthOnboardingRoute._addFileChildren(
  AuthOnboardingRouteChildren,
)

interface AuthRouteChildren {
  AuthAppRoute: typeof AuthAppRouteWithChildren
  AuthFeedbackRoute: typeof AuthFeedbackRoute
  AuthOnboardingRoute: typeof AuthOnboardingRouteWithChildren
  AuthPaymentSuccessRoute: typeof AuthPaymentSuccessRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppRoute: AuthAppRouteWithChildren,
  AuthFeedbackRoute: AuthFeedbackRoute,
  AuthOnboardingRoute: AuthOnboardingRouteWithChildren,
  AuthPaymentSuccessRoute: AuthPaymentSuccessRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoadingRoute: LoadingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
