on:
  issues: 
    types: 
      - opened

name: add-issue-to-project
jobs:
  add-issue-to-project:
    uses: Notifycal/gh-actions/.github/workflows/add-issue-to-project.yaml@main
    with:
      issue-node-id: ${{ github.event.issue.node_id }}
      
